name: Create and publish a Docker image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to build'
        required: true
        default: 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.event.inputs.ref == 'main' && 'latest' || github.event.inputs.ref }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: siyuan-note/siyuan
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/patch

      - name: Apply Patch
        run: git apply --ignore-space-change --ignore-whitespace ${{ github.workspace }}/patch/*.patch && rm -rf ${{ github.workspace }}/patch


      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest